In [4]:
import cv2

# Load the image
image = cv2.imread("tiger.jpg")

# Check if the image was loaded properly
if image is None:
    print("❌ Failed to load image. Check the file path.")
else:
    # Display the image in a window
    cv2.imshow("Tiger Image", image)

    # Wait for a key press and close the window
    cv2.waitKey(0)
    cv2.destroyAllWindows()


In [2]:
import cv2
import numpy as np

# Read the image
image1 = cv2.imread("tiger.jpg")

# Optional: check if image is loaded
if image1 is None:
    print("❌ Failed to load image. Check the file path.")
else:
    # Save a copy of the image
    cv2.imwrite("tiger_copy.jpg", image1)

    # Show the image in a window
    cv2.imshow("Tiger Image", image1)

    # Wait for a key press and close the window
    cv2.waitKey(0)
    cv2.destroyAllWindows()


In [7]:
image1

array([[[ 82, 130, 164],
        [ 79, 127, 161],
        [ 73, 121, 155],
        ...,
        [ 32,  62,  81],
        [ 30,  60,  79],
        [ 28,  58,  77]],

       [[ 80, 128, 162],
        [ 80, 128, 162],
        [ 77, 125, 159],
        ...,
        [ 30,  58,  75],
        [ 28,  55,  75],
        [ 26,  54,  71]],

       [[ 79, 127, 161],
        [ 80, 128, 162],
        [ 81, 129, 163],
        ...,
        [ 26,  52,  68],
        [ 25,  51,  68],
        [ 23,  49,  65]],

       ...,

       [[147, 172, 198],
        [141, 166, 192],
        [126, 151, 177],
        ...,
        [128, 158, 187],
        [127, 157, 186],
        [120, 150, 179]],

       [[146, 171, 197],
        [144, 169, 195],
        [134, 159, 185],
        ...,
        [144, 174, 201],
        [143, 173, 200],
        [136, 166, 193]],

       [[155, 180, 206],
        [154, 179, 205],
        [147, 172, 198],
        ...,
        [132, 162, 189],
        [131, 161, 188],
        [124, 154, 181]]

In [8]:
image1.shape

(406, 612, 3)

In [16]:
b,g,r = cv2.split(image1)
k = np.zeros_like(b)
b_only = cv2.merge([b,k,k])
g_only = cv2.merge([k,g,k])
r_only = cv2.merge([k,k,r])

cv2.imshow("red",r_only)
cv2.imshow("green",g_only)
cv2.imshow("blue",b_only)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
b,g,r= cv2.split(image1)
a.shape
b.shape
c.shape
cv2.imshow("blue",b)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
k=np.zeros_like(b).shape

In [34]:
b.shape, b_only.shape

Gray = 0.114 * b + 0.587 * g + 0.299 * r
Gray

array([[134.694, 131.694, 125.694, ...,  64.261,  62.261,  60.261],
       [132.694, 132.694, 129.694, ...,  59.891,  57.902,  55.891],
       [131.694, 132.694, 133.694, ...,  53.82 ,  53.119,  50.82 ],
       ...,
       [176.924, 170.924, 155.924, ..., 163.251, 162.251, 155.251],
       [175.924, 173.924, 163.924, ..., 178.653, 177.653, 170.653],
       [184.924, 183.924, 176.924, ..., 166.653, 165.653, 158.653]],
      shape=(406, 612))

In [38]:
gray=cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)

cv2.imshow("color",image1)
cv2.imshow("Gray", gray)
print('Gray Image Size : ',Gray.shape)

cv2.waitKey(0)
cv2.destroyAllWindows()

Gray Image Size :  (406, 612)


In [26]:
gray==r
gray.shape 
gray

array([[135, 132, 126, ...,  64,  62,  60],
       [133, 133, 130, ...,  60,  58,  56],
       [132, 133, 134, ...,  54,  53,  51],
       ...,
       [177, 171, 156, ..., 163, 162, 155],
       [176, 174, 164, ..., 179, 178, 171],
       [185, 184, 177, ..., 167, 166, 159]], shape=(406, 612), dtype=uint8)

In [27]:
r

array([[164, 161, 155, ...,  81,  79,  77],
       [162, 162, 159, ...,  75,  75,  71],
       [161, 162, 163, ...,  68,  68,  65],
       ...,
       [198, 192, 177, ..., 187, 186, 179],
       [197, 195, 185, ..., 201, 200, 193],
       [206, 205, 198, ..., 189, 188, 181]], shape=(406, 612), dtype=uint8)

In [32]:
Gray = 0.114 * b + 0.587 * g + 0.299 * r
Gray

array([[134.694, 131.694, 125.694, ...,  64.261,  62.261,  60.261],
       [132.694, 132.694, 129.694, ...,  59.891,  57.902,  55.891],
       [131.694, 132.694, 133.694, ...,  53.82 ,  53.119,  50.82 ],
       ...,
       [176.924, 170.924, 155.924, ..., 163.251, 162.251, 155.251],
       [175.924, 173.924, 163.924, ..., 178.653, 177.653, 170.653],
       [184.924, 183.924, 176.924, ..., 166.653, 165.653, 158.653]],
      shape=(406, 612))

In [30]:
gray

array([[135, 132, 126, ...,  64,  62,  60],
       [133, 133, 130, ...,  60,  58,  56],
       [132, 133, 134, ...,  54,  53,  51],
       ...,
       [177, 171, 156, ..., 163, 162, 155],
       [176, 174, 164, ..., 179, 178, 171],
       [185, 184, 177, ..., 167, 166, 159]], shape=(406, 612), dtype=uint8)

In [37]:
gray_8bit = Gray.astype(np.uint8)
gray_8bit

array([[134, 131, 125, ...,  64,  62,  60],
       [132, 132, 129, ...,  59,  57,  55],
       [131, 132, 133, ...,  53,  53,  50],
       ...,
       [176, 170, 155, ..., 163, 162, 155],
       [175, 173, 163, ..., 178, 177, 170],
       [184, 183, 176, ..., 166, 165, 158]], shape=(406, 612), dtype=uint8)

In [39]:
gray=cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)

cv2.imshow("color",image1)
cv2.imshow("Gray", gray)
print('Gray Image Size : ',Gray.shape)

cv2.waitKey(0)
cv2.destroyAllWindows()

Gray Image Size :  (406, 612)


In [40]:
#f
cv2.imshow("original",image1)
flipped = cv2.flip(image1, 1)
cv2.imshow("flipped horizontally",flipped)
flipped2 = cv2.flip(image1, 0)
cv2.imshow("flipped vertically",image1)
cropped_image = image1[80:280, 150:330]
cv2.imshow("Cropped",cropped_image)

cv2.waitKey(0)
cv2.destroyAllWindows()